# TP 1 : Preprocessing et Pipelines

**Objectif :**
Apprendre à préparer les données et automatiser le workflow ML avec les pipelines scikit-learn.
3 étapes clés :

Prétraitement manuel → encoder + normaliser les données correctement
Pipeline simple → automatiser ces étapes en une seule commande
Pipeline avancée → gérer colonnes mixtes, sélection de features et modèle dans une seule pipeline

---
###  Importation des Bibliothèques

In [36]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures, MinMaxScaler, OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.model_selection import train_test_split
import seaborn as sns

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

## 1. Génération d'un Dataset Synthétique

---
####  Chargement du Dataset Diamonds

On utilise le dataset **Diamonds** disponible via `seaborn`. Il contient ~54 000 observations avec les variables :
- **Numériques** : carat, depth, table, price, x, y, z
- **Catégorielles** : cut (coupe), color (couleur), clarity (clarté)

In [37]:
# Charger le dataset depuis Seaborn
df = sns.load_dataset("diamonds")

# Afficher les 5 premières lignes
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

## 2. Preprocessing des Variables Numériques

### Train Test Split

####  Séparation Train / Test

On divise le dataset en deux parties :
- **80%** → `train_set` : sert à ajuster (fit) les transformateurs et le modèle
- **20%** → `test_set` : sert à évaluer les performances (jamais vu pendant l'entraînement)

> `random_state=0` assure la reproductibilité des résultats.

In [38]:
train_set, test_set = train_test_split(df,test_size=0.2, random_state=0)

####  Vérification des dimensions

On vérifie que la séparation a bien été effectuée et que les proportions 80/20 sont respectées.

In [39]:
print("train_set :",train_set.shape)
print("test_set :",test_set.shape)

train_set : (43152, 10)
test_set : (10788, 10)

### Encoding
Commencez par explorer votre jeu de données et identifiez les variables catégoriques.<br>
Choisissez ensuite entre OrdinalEncoder et OneHotEncoder pour encoder ces variables : <br>
    - Si les catégories suivent un ordre naturel (ex. : "petit", "moyen", "grand"), utilisez OrdinalEncoder.<br>
    - Si elles n'ont pas d'ordre particulier (ex. : "rouge", "bleu", "vert"), utilisez OneHotEncoder.<br>
    - Faites une recherche sur Internet sur la classification des diamants afin de déterminer la méthode d'encodage la plus appropriée.

---
####  Exploration des Variables Catégorielles

Avant d'encoder, on explore les **valeurs uniques** de chaque colonne catégorielle (`cut`, `color`, `clarity`) pour décider quelle méthode utiliser :
- Si les catégories ont un **ordre naturel** → `OrdinalEncoder`
- Si elles sont **nominales** (sans ordre) → `OneHotEncoder`

Après recherche sur la classification des diamants, les 3 variables ont un ordre → on utilise `OrdinalEncoder`.

In [40]:
# Déterminer les différentes valeurs qui se cachent dans la première colonne catégorielle
valeurs_cut = df['cut'].unique()
print(valeurs_cut)

['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Categories (5, str): ['Ideal', 'Premium', 'Very Good', 'Good', 'Fair']

In [41]:
# Déterminer les différentes valeurs qui se cachent dans la deuxième colonne catégorielle
valeurs_color = df['color'].unique()
print(valeurs_color)

['E', 'I', 'J', 'H', 'F', 'G', 'D']
Categories (7, str): ['D', 'E', 'F', 'G', 'H', 'I', 'J']

In [42]:
# Déterminer les différentes valeurs qui se cachent dans  la troisième colonne catégorielle
valeurs_clarity = df['clarity'].unique()
print(valeurs_clarity)

['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF']
Categories (8, str): ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1']

####  Application de l'OrdinalEncoder

On définit l'ordre croissant de chaque catégorie (du moins bon au meilleur) :
- **cut** : `Fair < Good < Very Good < Premium < Ideal`
- **color** : `D` (meilleure transparence) → `J` (moins bonne)
- **clarity** : `IF` (parfaite) → `I1` (inclusions visibles)

L'encodeur transforme ces chaînes de caractères en entiers ordonnés.

In [43]:
#A l'aide d'une petite recherche sur internet, spécifiez l'ordre de chaque catégorie
cut_order = ['Fair','Good', 'Very Good', 'Premium', 'Ideal']
color_order = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_order = ['IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'I1']
#Introduire cut_order color_order dans l'Encoder
encoder = OrdinalEncoder(categories=[cut_order, color_order, clarity_order])
encoding_results = encoder.fit_transform(train_set[['cut','color','clarity']])
encoding_results

array([[4., 3., 3.],
       [4., 3., 4.],
       [4., 1., 2.],
       ...,
       [3., 5., 3.],
       [4., 3., 0.],
       [4., 2., 6.]], shape=(43152, 3))

In [44]:
train_set

       carat        cut color clarity  depth  table  price     x     y     z
26250   1.63      Ideal     G     VS1   61.7   55.0  15697  7.56  7.60  4.68
31510   0.34      Ideal     G     VS2   62.2   57.0    765  4.47  4.44  2.77
40698   0.40      Ideal     E    VVS2   61.7   56.0   1158  4.73  4.77  2.93
42634   0.58    Premium     H     SI1   62.1   55.0   1332  5.38  5.35  3.33
47714   0.63  Very Good     D     SI1   62.8   57.0   1885  5.40  5.46  3.41
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
45891   0.52    Premium     F     VS2   60.7   59.0   1720  5.18  5.14  3.13
52416   0.70       Good     D     SI1   63.6   60.0   2512  5.59  5.51  3.51
42613   0.32    Premium     I     VS1   61.3   58.0    505  4.35  4.39  2.68
43567   0.41      Ideal     G      IF   61.0   57.0   1431  4.81  4.79  2.93
2732    0.91      Ideal     F     SI2   61.1   55.0   3246  6.24  6.19  3.80

[43152 rows x 10 columns]

In [45]:
#injecter le résultat de l'encodage dans le tableau de trainset

train_set[['cut','color','clarity']]=encoding_results

train_set

       carat  cut  color  clarity  depth  table  price     x     y     z
26250   1.63  4.0    3.0      3.0   61.7   55.0  15697  7.56  7.60  4.68
31510   0.34  4.0    3.0      4.0   62.2   57.0    765  4.47  4.44  2.77
40698   0.40  4.0    1.0      2.0   61.7   56.0   1158  4.73  4.77  2.93
42634   0.58  3.0    4.0      5.0   62.1   55.0   1332  5.38  5.35  3.33
47714   0.63  2.0    0.0      5.0   62.8   57.0   1885  5.40  5.46  3.41
...      ...  ...    ...      ...    ...    ...    ...   ...   ...   ...
45891   0.52  3.0    2.0      4.0   60.7   59.0   1720  5.18  5.14  3.13
52416   0.70  1.0    0.0      5.0   63.6   60.0   2512  5.59  5.51  3.51
42613   0.32  3.0    5.0      3.0   61.3   58.0    505  4.35  4.39  2.68
43567   0.41  4.0    3.0      0.0   61.0   57.0   1431  4.81  4.79  2.93
2732    0.91  4.0    2.0      6.0   61.1   55.0   3246  6.24  6.19  3.80

[43152 rows x 10 columns]

## Normalisation

---
###  Normalisation avec MinMaxScaler

Après l'encodage, on normalise toutes les variables dans l'intervalle **[0, 1]** grâce à `MinMaxScaler`.

**Formule** : `x_norm = (x - x_min) / (x_max - x_min)`

>  On applique `.fit_transform()` **uniquement sur le train set** pour ne pas laisser fuiter d'information du test set.

In [46]:
scaler = MinMaxScaler()
trani_set = scaler.fit_transform(train_set)
train_set

       carat  cut  color  clarity  depth  table  price     x     y     z
26250   1.63  4.0    3.0      3.0   61.7   55.0  15697  7.56  7.60  4.68
31510   0.34  4.0    3.0      4.0   62.2   57.0    765  4.47  4.44  2.77
40698   0.40  4.0    1.0      2.0   61.7   56.0   1158  4.73  4.77  2.93
42634   0.58  3.0    4.0      5.0   62.1   55.0   1332  5.38  5.35  3.33
47714   0.63  2.0    0.0      5.0   62.8   57.0   1885  5.40  5.46  3.41
...      ...  ...    ...      ...    ...    ...    ...   ...   ...   ...
45891   0.52  3.0    2.0      4.0   60.7   59.0   1720  5.18  5.14  3.13
52416   0.70  1.0    0.0      5.0   63.6   60.0   2512  5.59  5.51  3.51
42613   0.32  3.0    5.0      3.0   61.3   58.0    505  4.35  4.39  2.68
43567   0.41  4.0    3.0      0.0   61.0   57.0   1431  4.81  4.79  2.93
2732    0.91  4.0    2.0      6.0   61.1   55.0   3246  6.24  6.19  3.80

[43152 rows x 10 columns]

### Transformation du test set

---
###  Transformation du Test Set

On applique les **mêmes paramètres** appris sur le train set au test set :
1. `encoder.transform()` → encodage avec les ordres déjà appris
2. `scaler.transform()` → normalisation avec min/max du train set

>  **Important** : on utilise `.transform()` (et non `.fit_transform()`) sur le test set pour éviter la **fuite de données (data leakage)**.

In [47]:
encoding_results = encoder.transform(test_set[['cut','color','clarity']])

In [48]:
#injecter le résultat de l'encodage dans le tableau de testset
test_set[['cut','color','clarity']] = encoding_results
test_set

       carat  cut  color  clarity  depth  table  price     x     y     z
10176   1.10  4.0    4.0      6.0   62.0   55.0   4733  6.61  6.65  4.11
16083   1.29  4.0    4.0      5.0   62.6   56.0   6424  6.96  6.93  4.35
13420   1.20  3.0    5.0      5.0   61.1   58.0   5510  6.88  6.80  4.18
20407   1.50  4.0    2.0      5.0   60.9   56.0   8770  7.43  7.36  4.50
8909    0.90  2.0    2.0      4.0   61.7   57.0   4493  6.17  6.21  3.82
...      ...  ...    ...      ...    ...    ...    ...   ...   ...   ...
42208   0.52  1.0    4.0      4.0   63.6   57.0   1289  5.05  5.10  3.23
3638    0.91  2.0    3.0      6.0   60.4   61.0   3435  6.21  6.28  3.77
5508    1.08  2.0    2.0      6.0   63.4   55.0   3847  6.53  6.50  4.13
19535   1.02  4.0    3.0      1.0   61.5   57.0   8168  6.44  6.47  3.97
47950   0.50  1.0    1.0      2.0   64.8   58.0   1917  4.97  5.00  3.23

[10788 rows x 10 columns]

In [49]:
test_set = scaler.transform(test_set)
test_set

array([[0.18711019, 1.        , 0.66666667, ..., 0.61545624, 0.11290323,
        0.12924528],
       [0.22661123, 1.        , 0.66666667, ..., 0.64804469, 0.11765705,
        0.13679245],
       [0.20790021, 0.75      , 0.83333333, ..., 0.6405959 , 0.11544992,
        0.13144654],
       ...,
       [0.18295218, 0.5       , 0.33333333, ..., 0.60800745, 0.11035654,
        0.12987421],
       [0.17047817, 1.        , 0.5       , ..., 0.59962756, 0.1098472 ,
        0.12484277],
       [0.06237006, 0.25      , 0.16666667, ..., 0.46275605, 0.08488964,
        0.10157233]], shape=(10788, 10))

## Simplifier le tout avec une Pipeline

---
##  Pipelines Scikit-learn

L'objet `Pipeline` enchaîne automatiquement plusieurs étapes de prétraitement (et éventuellement un modèle) dans un seul objet cohérent.

**Avantages :**
- Élimine les risques de **fuite de données**
- Rend le code plus **lisible et maintenable**
- Facilite le **déploiement** en production

In [50]:
from sklearn.pipeline import Pipeline, make_pipeline

In [51]:
df = sns.load_dataset("diamonds")
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [52]:
train_set, test_set = train_test_split(df,test_size=0.2,random_state=0)

####  Pipeline Simple : Encoder → Scaler

Première pipeline de base : `OrdinalEncoder` + `MinMaxScaler`.
Un seul appel à `.fit_transform()` exécute les deux étapes dans l'ordre.

In [53]:
pipeline = Pipeline(steps=[("Encoder",OrdinalEncoder()),
                           ("Normaliser",MinMaxScaler())])

In [54]:
pipeline

Pipeline(steps=[('Encoder', OrdinalEncoder()), ('Normaliser', MinMaxScaler())])

In [55]:
pipeline.fit_transform(train_set)

array([[0.53358209, 0.5       , 0.5       , ..., 0.69652651, 0.70879121,
        0.67486339],
       [0.05223881, 0.5       , 0.5       , ..., 0.13162706, 0.13003663,
        0.15300546],
       [0.07462687, 0.5       , 0.16666667, ..., 0.17915905, 0.19047619,
        0.19672131],
       ...,
       [0.04477612, 0.75      , 0.83333333, ..., 0.10968921, 0.12087912,
        0.1284153 ],
       [0.07835821, 0.5       , 0.5       , ..., 0.19378428, 0.19413919,
        0.19672131],
       [0.26492537, 0.5       , 0.33333333, ..., 0.45521024, 0.45054945,
        0.43442623]], shape=(43152, 10))

### Pipeline composée

<img src="pipeline.png" alt="Texte alternatif" width="450" height="500">

---
###  Pipeline Composée avec ColumnTransformer

`ColumnTransformer` permet d'appliquer des **transformations différentes** à des colonnes différentes :
- Colonnes catégorielles → `OrdinalEncoder` avec ordres définis
- Colonnes numériques → `passthrough` (inchangées)

On intègre ensuite ce `ColumnTransformer` comme première étape d'une `Pipeline` pour ajouter la normalisation.

In [56]:
from sklearn.compose import ColumnTransformer

In [57]:
# définir une liste des variables catégorielles 
categorical_cols = ["cut","color","clarity"]

In [58]:
column_transformer = ColumnTransformer(transformers=[("Encoder",OrdinalEncoder(categories=[cut_order, color_order, clarity_order]),categorical_cols)],
                                       remainder="passthrough")
#Intégrer column_transformer dans une pipeline
pipeline = Pipeline(steps=[("Encoder",column_transformer),
                           ("Scaler",MinMaxScaler())
                          ])
pipeline.fit_transform(train_set)

array([[1.        , 0.5       , 0.42857143, ..., 0.70391061, 0.12903226,
        0.14716981],
       [1.        , 0.5       , 0.57142857, ..., 0.41620112, 0.075382  ,
        0.08710692],
       [1.        , 0.16666667, 0.28571429, ..., 0.44040968, 0.08098472,
        0.09213836],
       ...,
       [0.75      , 0.83333333, 0.42857143, ..., 0.40502793, 0.07453311,
        0.08427673],
       [1.        , 0.5       , 0.        , ..., 0.44785847, 0.08132428,
        0.09213836],
       [1.        , 0.33333333, 0.85714286, ..., 0.58100559, 0.10509338,
        0.11949686]], shape=(43152, 10))

In [59]:
pipeline.transform(test_set)

array([[1.        , 0.66666667, 0.85714286, ..., 0.61545624, 0.11290323,
        0.12924528],
       [1.        , 0.66666667, 0.71428571, ..., 0.64804469, 0.11765705,
        0.13679245],
       [0.75      , 0.83333333, 0.71428571, ..., 0.6405959 , 0.11544992,
        0.13144654],
       ...,
       [0.5       , 0.33333333, 0.85714286, ..., 0.60800745, 0.11035654,
        0.12987421],
       [1.        , 0.5       , 0.14285714, ..., 0.59962756, 0.1098472 ,
        0.12484277],
       [0.25      , 0.16666667, 0.28571429, ..., 0.46275605, 0.08488964,
        0.10157233]], shape=(10788, 10))

### Exercice : Création des pipelines
<img src="./pipelineImage/pipe1.png" width="200">

---

#### Pipeline Niveau 1 — Feature Engineering + Sélection + Normalisation

Cette pipeline enchaîne trois étapes :
1. **`PolynomialFeatures(degree=2)`** : génère des features polynomiales (termes croisés et carrés) — enrichit le jeu de données
2. **`SelectKBest(f_regression, k=5)`** : conserve les 5 meilleures features selon leur corrélation avec la cible
3. **`MinMaxScaler`** : normalise les features sélectionnées dans [0,1]

>  Très utile pour la régression sur des données peu nombreuses.

In [60]:
from sklearn.feature_selection import SelectKBest, f_regression, f_classif
pipeNiveau1 = Pipeline(steps=[
    ("FeatureEngineering",PolynomialFeatures(degree = 2, include_bias=True)),
    ("SelectFeatures", SelectKBest(score_func=f_regression, k=5)),
    ("Normalisation",MinMaxScaler())])
pipeNiveau1

Pipeline(steps=[('FeatureEngineering', PolynomialFeatures()),
                ('SelectFeatures',
                 SelectKBest(k=5,
                             score_func=<function f_regression at 0x000001A078E88360>)),
                ('Normalisation', MinMaxScaler())])

In [61]:
# Création d’un jeu de données de régression pour tester la pipeline
from sklearn.datasets import make_regression
X, y =make_regression (n_samples = 100, n_features = 4, noise = 0.1, random_state = 42)
pipeNiveau1.fit_transform(X,y)

array([[6.03262586e-01, 3.69231960e-01, 0.00000000e+00, 2.56728701e-01,
        2.33507240e-03],
       [3.17470504e-01, 2.30020341e-01, 5.31391733e-01, 2.82829305e-01,
        2.61159206e-02],
       [1.79406459e-01, 3.63601033e-01, 2.62980978e-01, 1.97733130e-01,
        1.58498975e-03],
       [5.01996265e-01, 3.56237034e-01, 3.41204541e-01, 2.36055325e-01,
        8.21851895e-04],
       [1.68098199e-01, 3.05211385e-01, 3.56230227e-01, 2.67861072e-01,
        2.31513390e-03],
       [6.06092365e-01, 3.17413318e-01, 2.84027264e-01, 2.11196626e-01,
        8.79832415e-04],
       [3.72361791e-01, 3.82066750e-01, 5.34877701e-01, 2.17912274e-01,
        4.58419083e-03],
       [5.31328384e-01, 1.75804281e-01, 1.49194213e-01, 1.43762821e-01,
        5.92457930e-02],
       [1.18406659e-01, 1.22477246e-01, 4.08446003e-01, 5.43306317e-01,
        1.04885300e-01],
       [2.59194826e-01, 5.02191890e-01, 8.01024303e-01, 9.89395779e-02,
        6.19867159e-02],
       [2.50496227e-01, 3.68696500e-01, 6.67648844e-01, 2.02582661e-01,
        2.25753507e-03],
       [1.60736342e-01, 2.81743884e-01, 2.86162718e-01, 2.98593970e-01,
        6.98079003e-03],
       [4.16559929e-01, 3.24345139e-01, 5.25990223e-01, 2.29056533e-01,
        3.66322132e-04],
       [4.59275068e-01, 4.06668558e-01, 4.29479787e-01, 2.41144037e-01,
        1.09915513e-02],
       [4.24866737e-01, 2.68124909e-01, 6.25670735e-01, 2.27817860e-01,
        1.08380000e-02],
       [7.51423138e-01, 4.18632902e-01, 2.21862440e-01, 3.58114909e-01,
        1.51033148e-02],
       [1.17191474e-01, 3.59646638e-01, 3.65246712e-01, 1.95613686e-01,
        1.14450481e-03],
       [7.48895843e-01, 2.26163031e-01, 5.49974187e-01, 5.37865170e-02,
        2.80308955e-02],
       [3.14508945e-01, 3.79078646e-01, 2.77183712e-01, 2.06929976e-01,
        3.99359991e-03],
       [3.01901074e-01, 7.14012215e-01, 6.01870820e-01, 1.00246566e-02,
        3.23239941e-01],
       [4.86245457e-01, 7.60944018e-01, 4.80522661e-01, 3.59656937e-01,
        4.08763665e-01],
       [1.59259798e-01, 4.51070138e-01, 4.92801365e-01, 8.42187680e-02,
        2.95290348e-02],
       [2.70452067e-01, 3.77111557e-01, 3.09949193e-01, 1.99459485e-01,
        3.62699493e-03],
       [8.25101531e-01, 4.08170531e-01, 6.88630334e-01, 3.66739699e-01,
        1.14719656e-02],
       [3.94547409e-01, 2.83773125e-01, 6.23783317e-01, 2.35827142e-01,
        6.47833492e-03],
       [6.29413530e-01, 2.83954526e-01, 2.73267143e-01, 1.75529360e-01,
        6.43433116e-03],
       [6.04104914e-01, 7.65299662e-02, 2.71521396e-01, 0.00000000e+00,
        1.54590724e-01],
       [5.81914690e-01, 1.36086963e-01, 4.58645626e-01, 7.37870978e-02,
        9.20072490e-02],
       [6.35358586e-01, 5.70488822e-01, 6.53870606e-01, 4.68650238e-01,
        1.23912172e-01],
       [3.02447659e-01, 2.81860131e-01, 2.76428654e-01, 2.60648284e-01,
        6.95150025e-03],
       [5.90353915e-01, 1.28257055e-01, 2.34832235e-01, 5.92498582e-02,
        9.93132149e-02],
       [2.31600511e-01, 4.45257538e-01, 6.10457095e-01, 1.29316510e-01,
        2.65917800e-02],
       [3.10513004e-01, 2.34030194e-01, 2.73150935e-01, 2.84264734e-01,
        2.41970152e-02],
       [5.47160032e-01, 1.30450799e-03, 9.58148960e-01, 2.62442698e-02,
        2.56715646e-01],
       [6.85124187e-01, 5.70081477e-01, 7.18945515e-02, 5.24150026e-01,
        1.23479886e-01],
       [5.24676880e-01, 1.89682792e-01, 6.10813685e-01, 1.55801313e-01,
        4.94908591e-02],
       [5.85207502e-01, 2.96870946e-01, 4.12689234e-01, 1.97031198e-01,
        3.68616821e-03],
       [2.47865658e-01, 4.72567952e-01, 2.42052776e-01, 1.14832079e-01,
        4.17287136e-02],
       [6.27947828e-01, 4.25458824e-01, 3.44573940e-01, 3.16357335e-01,
        1.77410915e-02],
       [5.86736756e-01, 2.15401609e-01, 7.58572483e-01, 1.32066853e-01,
        3.37315015e-02],
       [4.64008429e-01, 0.00000000e+00, 5.14771554e-01, 1.60697313e-01,
        2.58713850e-01],
       [3.19332727e-01, 5.14784694e-01, 9.55642583e-01, 1.40569514e-01,
        7.18081618e-02],
       [4.68171225e-01, 4.54075277e-01, 3.01820021e-01, 2.54642244e-01,
        3.11079193e-02],
       [3.90954531e-01, 2.20650343e-01, 4.84111385e-01, 2.46264199e-01,
        3.08852541e-02],
       [2.48900557e-01, 2.07476021e-01, 4.10100465e-01, 3.37112743e-01,
        3.82669834e-02],
       [3.40394178e-01, 3.38293844e-02, 5.45822445e-01, 3.48397288e-01,
        2.09399363e-01],
       [8.66648934e-01, 4.39547595e-01, 4.88994421e-01, 4.48247293e-01,
        2.38561468e-02],
       [3.58232593e-01, 3.66636469e-01, 6.36805482e-01, 2.19611852e-01,
        1.97140162e-03],
       [1.41705484e-01, 4.71662693e-01, 5.26527668e-01, 4.67091223e-02,
        4.11725640e-02],
       [4.95783131e-01, 3.88248257e-01, 5.86912640e-01, 2.46847411e-01,
        5.93495908e-03],
       [6.20010923e-01, 4.42389667e-01, 3.10664138e-01, 3.29133016e-01,
        2.51992319e-02],
       [6.17160686e-01, 4.06828707e-01, 8.73449426e-01, 2.94240085e-01,
        1.10422869e-02],
       [7.45708175e-01, 3.13365446e-01, 5.81099606e-01, 1.91584449e-01,
        1.28085589e-03],
       [4.06721863e-01, 4.59994129e-01, 4.15152616e-01, 2.19541289e-01,
        3.43378728e-02],
       [6.46741830e-01, 2.13306994e-01, 1.25955217e-01, 9.45552905e-02,
        3.49023633e-02],
       [5.04039573e-01, 1.22828977e-01, 5.15976712e-01, 1.44086590e-01,
        1.04541864e-01],
       [3.22531381e-01, 6.52248269e-01, 1.62428958e-01, 7.72233782e-02,
        2.25967672e-01],
       [8.20721053e-01, 3.63027893e-01, 2.91720722e-01, 2.78452452e-01,
        1.51673620e-03],
       [0.00000000e+00, 2.85710259e-01, 4.86701943e-01, 3.33479676e-01,
        6.01617340e-03],
       [5.96777342e-01, 6.06343817e-01, 4.58388870e-01, 4.55419912e-01,
        1.64921733e-01],
       [5.51844460e-01, 2.40776391e-01, 2.75622669e-01, 1.68430491e-01,
        2.11337927e-02],
       [5.83409291e-01, 4.49222464e-01, 6.86470243e-01, 3.15865824e-01,
        2.85786841e-02],
       [5.20350187e-01, 3.38913811e-01, 7.34666457e-01, 2.29542203e-01,
        0.00000000e+00],
       [2.96532539e-01, 3.57338953e-01, 4.61827840e-01, 2.16472426e-01,
        9.20339472e-04],
       [1.22195671e-01, 3.91218227e-01, 2.33262177e-01, 1.50467045e-01,
        6.64581137e-03],
       [5.97899058e-01, 3.95847061e-01, 4.48877911e-01, 2.78457875e-01,
        7.83376305e-03],
       [1.00000000e+00, 5.87227867e-01, 4.69640061e-01, 9.25750094e-01,
        1.42329357e-01],
       [2.75006659e-01, 4.83323832e-01, 3.30839543e-01, 1.24924729e-01,
        4.86221011e-02],
       [2.51775189e-01, 2.64782942e-01, 1.40506863e-01, 2.88203228e-01,
        1.19135341e-02],
       [8.15645865e-01, 2.86968535e-01, 3.28241743e-01, 1.33457266e-01,
        5.72512541e-03],
       [6.55589949e-01, 3.02366834e-01, 5.92709177e-01, 1.89542269e-01,
        2.74715068e-03],
       [1.93261418e-01, 5.24502765e-01, 3.57899053e-01, 2.18080114e-02,
        7.98810160e-02],
       [7.35581520e-01, 3.00430543e-01, 3.01096368e-01, 1.73191710e-01,
        3.06229457e-03],
       [6.46036571e-01, 4.33633946e-01, 5.49087357e-01, 3.32890531e-01,
        2.11793675e-02],
       [4.26653463e-01, 4.77114271e-01, 6.56840909e-01, 2.31720861e-01,
        4.45781723e-02],
       [5.07521998e-01, 6.00854736e-01, 5.86314675e-01, 3.37256153e-01,
        1.58264164e-01],
       [2.46474623e-01, 2.87490713e-01, 4.62378201e-01, 2.70805334e-01,
        5.60645787e-03],
       [2.04595340e-01, 3.26912160e-01, 2.53055860e-01, 2.39458442e-01,
        2.31654764e-04],
       [1.19552260e-01, 2.98309363e-01, 8.04366659e-01, 2.85417817e-01,
        3.42711923e-03],
       [1.23223750e-01, 3.77076501e-01, 3.58104951e-01, 1.71130604e-01,
        3.62062131e-03],
       [4.61411135e-01, 5.62041837e-01, 5.19056621e-01, 2.71255845e-01,
        1.15102565e-01],
       [5.61654552e-01, 4.18674277e-01, 8.96565755e-01, 2.83553039e-01,
        1.51186648e-02],
       [1.24415981e-01, 1.80696851e-01, 6.48917873e-01, 4.53452688e-01,
        5.57068371e-02],
       [3.23263345e-01, 4.30498498e-01, 3.58465318e-01, 1.84161468e-01,
        1.98247024e-02],
       [1.62864894e-01, 1.55178402e-01, 4.63533994e-01, 4.56356938e-01,
        7.53631270e-02],
       [4.39583303e-01, 2.96409579e-01, 2.88565611e-01, 2.25290335e-01,
        3.77125215e-03],
       [1.11317571e-01, 2.80780319e-01, 3.04873299e-01, 3.13248306e-01,
        7.22593963e-03],
       [2.09238393e-01, 3.09636483e-01, 6.64270576e-01, 2.56976077e-01,
        1.71628854e-03],
       [2.83414170e-01, 2.79603681e-01, 1.90065432e-01, 2.67235746e-01,
        7.53103036e-03],
       [5.55935294e-01, 3.90022885e-01, 6.73934671e-01, 2.62818737e-01,
        6.35488205e-03],
       [3.02752906e-01, 7.98118958e-03, 5.22398326e-01, 4.18368040e-01,
        2.46609799e-01],
       [5.27974828e-01, 2.04160073e-01, 4.89151141e-01, 1.60842849e-01,
        4.02494033e-02],
       [5.26683525e-01, 2.37899333e-01, 6.85645798e-01, 1.78678087e-01,
        2.24148324e-02],
       [3.12102898e-01, 3.98593017e-01, 4.16026135e-01, 1.96079919e-01,
        8.58458108e-03],
       [4.92023979e-01, 2.50828001e-01, 2.80346712e-01, 1.99628299e-01,
        1.69539875e-02],
       [6.63404484e-01, 1.00000000e+00, 5.85324116e-01, 1.00000000e+00,
        1.00000000e+00],
       [4.36755795e-01, 2.50532321e-01, 4.89606292e-01, 2.22622924e-01,
        1.70703759e-02],
       [3.40345043e-01, 2.33888388e-01, 5.12512487e-01, 2.69480372e-01,
        2.42636276e-02],
       [5.56846598e-01, 2.25048072e-01, 4.77145001e-01, 1.55888229e-01,
        2.85970391e-02],
       [7.96248723e-02, 1.58978917e-02, 1.00000000e+00, 7.59594699e-01,
        2.34890006e-01]])

---
#### Pipeline Niveau 2 — Preprocessing Mixte (Numérique + Catégoriel)

On génère un dataset mixte :
- 2 colonnes **numériques continues** (`X1`, `X2`)
- 1 colonne **catégorielle nominale** (`Ville` : Paris, Marseille, Belfort)

Le `ColumnTransformer` applique :
- `MinMaxScaler` sur les colonnes numériques
- `OneHotEncoder` sur la colonne catégorielle (pas d'ordre → on ne peut pas utiliser `OrdinalEncoder`)

In [62]:
#Création d’un jeu de données de régression pour tester la deuxième pipeline
np.random.seed(42)
n_samples = 100
X_numeric = np.random.rand(n_samples, 2) # 2 variables numériques
X_categorical = np.random.choice(['Paris','Marseille','Belfort'],size=(n_samples, 1))
df = pd.DataFrame(np.hstack((X_numeric,X_categorical)),columns=["X1","X2","Ville"])
df

                     X1                   X2      Ville
0    0.3745401188473625   0.9507143064099162    Belfort
1    0.7319939418114051   0.5986584841970366      Paris
2   0.15601864044243652  0.15599452033620265  Marseille
3   0.05808361216819946   0.8661761457749352  Marseille
4    0.6011150117432088   0.7080725777960455    Belfort
..                  ...                  ...        ...
95  0.09310276780589921   0.8972157579533268  Marseille
96   0.9004180571633305   0.6331014572732679    Belfort
97   0.3390297910487007   0.3492095746126609      Paris
98   0.7259556788702394   0.8971102599525771  Marseille
99   0.8870864242651173   0.7798755458576239    Belfort

[100 rows x 3 columns]

<img src="./pipelineImage/pipe2.png" width="300">

In [63]:
# Colonnes par type
num_cols = ["X1", "X2"]
cat_cols = ["Ville"]

# Assurer le bon type numérique (car df a été construit avec np.hstack)
df[num_cols] = df[num_cols].astype(float)

# Pipeline niveau 2 : prétraitement mixte (numérique + catégoriel)
pipeNiveau2 = Pipeline(steps=[
    ("Preprocessing", ColumnTransformer(
        transformers=[
            ("num", MinMaxScaler(), num_cols),
            ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
        ],
        remainder="drop"
    ))
])

pipeNiveau2

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('num', MinMaxScaler(),
                                                  ['X1', 'X2']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Ville'])]))])

In [64]:
pipeNiveau2.fit_transform(df).shape

(100, 5)

<img src="./pipelineImage/pipe3.png" width="350">

---
#### Pipeline Niveau 3 — Preprocessing Mixte + Sélection de Features

On ajoute une étape de **sélection de variables** :
1. `ColumnTransformer` : normalise les numériques + encode les catégorielles
2. `SelectKBest(f_regression, k=5)` : ne garde que les 5 features les plus informatives

>  Réduit la dimensionnalité et améliore la généralisation du modèle.

In [65]:
np.random.seed(42)
n_samples = 100
X_numeric = np.random.rand(n_samples, 2) # 2 variables numérique
X_categorical = np.random.choice(['A','B','C','D'],size = (n_samples,2)) # 2 variables catégorielles
y=np.random.rand(n_samples)*10 # variable cible
#création d'un DataFrame
df=pd.DataFrame(np.hstack((X_numeric,X_categorical)), columns=["X1","X2","Cat 1","Cat 2"])
df["y"]= y
#Définition des colonnes catégorielles
cat_cols = ["Cat 1","Cat 2"]
df['Cat 2']

0     D
1     A
2     D
3     D
4     B
     ..
95    D
96    D
97    D
98    C
99    B
Name: Cat 2, Length: 100, dtype: str

In [66]:
# Colonnes
num_cols = ["X1", "X2"]
cat_cols = ["Cat 1", "Cat 2"]

# Assurer le bon type des colonnes numériques
df[num_cols] = df[num_cols].astype(float)

# Séparer les variables explicatives et la cible
X = df.drop(columns=["y"])

y = df["y"]

# Pipeline de preprocessing + sélection de variables
pipelineNiveau3 = Pipeline(steps=[
    ("Preprocessing", ColumnTransformer(
        transformers=[
            ("num", MinMaxScaler(), num_cols),
            ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
        ],
        remainder="drop"
    )),
    ("SelectFeatures", SelectKBest(score_func=f_regression, k=5))
])

# Affichage de la pipeline
pipelineNiveau3

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(transformers=[('num', MinMaxScaler(),
                                                  ['X1', 'X2']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Cat 1', 'Cat 2'])])),
                ('SelectFeatures',
                 SelectKBest(k=5,
                             score_func=<function f_regression at 0x000001A078E88360>))])

In [67]:
# Appliquer la pipeline niveau 3 sur X et y
X_niv3 = pipelineNiveau3.fit_transform(X, y)
print("Shape après pipelineNiveau3:", X_niv3.shape)
pd.DataFrame(X_niv3).head()

Shape après pipelineNiveau3: (100, 5)

     0    1    2    3    4
0  0.0  0.0  1.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  1.0  0.0  0.0  0.0
4  0.0  0.0  1.0  1.0  0.0

<img src="./pipelineImage/pipe4.png" width="350">

---
#### Pipeline Niveau 4 — Pipeline Complète avec Modèle

La pipeline la plus complète intègre **tout le workflow ML** :
1. **`ColumnTransformer`** : prétraitement des features
2. **`SelectKBest`** : sélection des 5 meilleures features
3. **`LinearRegression`** : modèle de régression linéaire

Un seul `.fit()` entraîne toute la chaîne. Un seul `.predict()` applique tout le prétraitement + la prédiction.

>  **Bonne pratique en ML** : toujours intégrer le modèle dans la pipeline pour garantir l'absence de fuite de données et faciliter le déploiement.

In [68]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Pipeline complète : preprocessing + sélection + modèle
pipelineNiveau4 = Pipeline(steps=[
    ("Preprocessing", ColumnTransformer(
        transformers=[
            ("num", MinMaxScaler(), num_cols),
            ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
        ],
        remainder="drop"
    )),
    ("SelectFeatures", SelectKBest(score_func=f_regression, k=5)),
    ("Model", LinearRegression())
])

# Entraînement et évaluation
pipelineNiveau4.fit(X, y)
y_pred = pipelineNiveau4.predict(X)

print("R2:", round(r2_score(y, y_pred), 4))
print("MSE:", round(mean_squared_error(y, y_pred), 4))
pd.DataFrame({"y_reel": y.head(10), "y_pred": y_pred[:10]})

R2: 0.0893
MSE: 7.7636

     y_reel    y_pred
0  0.516817  3.996801
1  5.313546  5.035328
2  5.406351  3.996801
3  6.374299  6.306142
4  7.260913  4.211833
5  9.758521  5.035328
6  5.163003  6.306142
7  3.229565  5.035328
8  7.951862  5.421051
9  2.708323  4.211833

---
## Conclusion du TP 1

Ce TP nous a permis de maîtriser les étapes essentielles du **preprocessing** et de la construction de **pipelines scikit-learn** :

| Concept | Outil | Rôle |
|---|---|---|
| Séparation données | `train_test_split` | Éviter le data leakage |
| Encodage ordonné | `OrdinalEncoder` | Variables catégorielles ordonnées |
| Encodage nominal | `OneHotEncoder` | Variables sans ordre naturel |
| Normalisation | `MinMaxScaler` | Ramener dans [0,1] |
| Pipeline simple | `Pipeline` | Enchaîner des transformations |
| Pipeline composée | `ColumnTransformer` | Transformations par colonnes |
| Sélection features | `SelectKBest` | Réduire la dimensionnalité |
| Pipeline complète | `Pipeline` + modèle | Workflow ML complet |

>  La `Pipeline` est l'outil fondamental en ML pour un code propre, reproductible et sans fuite de données.